name: app_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # core
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.7

  # firebase
  firebase_core: ^4.3.0
  # localizations
  flutter_localization: ^0.3.3
  animate_do: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^10.0.0
  flutter_lints: ^6.0.0

  # app icon generator
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/icons/
    - lang/ar.json
    - lang/en.json
    - assets/images/admin/
    - assets/images/core/
    - assets/images/customer/
    

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
